# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "cruise_control_providers", :force => true do |t|
    t.column "server_id", :integer
    t.column "project",   :string
  end

  create_table "cruise_control_servers", :force => true do |t|
    t.column "url",             :string
    t.column "pollingInterval", :integer
  end

  create_table "dashboards", :force => true do |t|
    t.column "name", :string
  end

  create_table "measures", :force => true do |t|
    t.column "value",     :string
    t.column "timestamp", :datetime
    t.column "metric_id", :integer,  :null => false
  end

  add_index "measures", ["metric_id", "timestamp"], :name => "index_measures_on_metric_id_and_timestamp"

  create_table "metrics", :force => true do |t|
    t.column "name",          :string
    t.column "dashboard_id",  :integer, :null => false
    t.column "provider_type", :string,  :null => false
    t.column "provider_id",   :integer, :null => false
  end

end
